import Head from "next/head";
import AreasContainer from "../components/AreasContainer";
import Footer from "../components/Footer";
import Header from "../components/Header";
import OpeningSection from "../components/OpeningSection";

export default function Home() {
  return (
    <div className="bg-red-600">
      <Head>
        <title>Rethink Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen font-roboto bg-lime">
        <OpeningSection />
        <AreasContainer />
        <Footer />
      </main>
    </div>
  );
}
