import Head from "next/head";
import AreasContainer from "../components/AreasContainer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className="bg-red-600">
      <Head>
        <title>Rethink Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen font-roboto bg-lime">
        <div className=" bg-[url('../../public/background.jpg')] bg-cover bg-center bg-opacity-0 h-[80%]">
          <div className="absolute inset-0 bg-black bg-opacity-75 h-[80%] ">
            <Header />
            <div className="h-full w-full pl-[250px] pt-[80px] font-normal">
              <p className="align-middle mt-20 w-[900px] text-8xl text-lime">
                ¤Venha se tornar →→ um Rethinker®
              </p>
            </div>
          </div>
        </div>
        <div>
          <div className="h-[5px] bg-matter"></div>
          <div className="h-[5px] bg-product"></div>
          <div className="h-[5px] bg-coal"></div>
        </div>
        <AreasContainer />
      </main>
    </div>
  );
}
