import Head from "next/head";
import React, { ReactNode } from "react";
import { Menu, MenuAcordeon } from "../pages";
import Header from "./Header";

interface LayoutProps {
  children: ReactNode;
  MenuAcordeon: MenuAcordeon;
  TitleAcordeon: string;
  logo: string;
  menu: Menu;
}

const Layout = ({
  children,
  MenuAcordeon,
  TitleAcordeon,
  logo,
  menu,
}: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Rethink Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-black">
        <Header
          logo={logo}
          menu={menu}
          TitleAcordeon={TitleAcordeon}
          MenuAcordeon={MenuAcordeon}
        />
        {children}
      </main>
    </>
  );
};

export default Layout;
